### ISSUE TITLE
Literals are not "fully functional"

### ISSUE THREAD

**Issue by reece** [cwacek/python-jsonschema-objects#119]
The <Literal ...> wrapper does not support calling methods provided by the underlying value type. In this sense, the wrappers are not "fully functional" as claimed in README.md.

This change also breaks code that worked on releases prior to 0.3.0 that expected values to be exactly as passed during instantiation. Continuing from the example in README.md, `james.lastName.startswith("B")` works correctly on 0.2.4 but 0.3.1 gives `AttributeError: 'example_schema/firstName' object has no attribute 'startswith'`

**Comment by reece** [comment]
Closing. More than a year old, and for a much older pjo.
